chore: alignment updates. NOT TESTED. PENDING MORE USAGE OF deploy.sh in bitbucket pipelines

diff --git a/.gitlab/pipelines/deploy.yml b/.gitlab/pipelines/deploy.yml
--- a/.gitlab/pipelines/deploy.yml
+++ b/.gitlab/pipelines/deploy.yml
@@ -1,4 +1,5 @@
-image: salesforce/salesforcedx:latest-full
+default:
+    image: salesforce/salesforcedx:latest-full
 
 .sfdx-changes:
     - sfdx-source/**/main/**/*
@@ -49,6 +50,7 @@ deploy-deltas:
         - sfdx nps:package:destructive:versionobsoleteflows --path deltas/destructiveChanges/destructiveChanges.xml
         # RUN_TEST_PARAMETER can be uncommented to double also run tests on deployments to DEVINT, however it is redundant with MR and will take longer.
         # - RUN_TEST_PARAMETER=$(if [ $TEST_CLASSES ]; then echo "--testlevel RunSpecifiedTests --runtests $TEST_CLASSES"; else echo ""; fi)
+        - source .env.replacements # This does not work in  GitHub actions
         - sfdx force:source:deploy --wait 60 --manifest deltas/package/package.xml --postdestructivechanges deltas/destructiveChanges/destructiveChanges.xml --ignorewarnings
         - |
             curl --request PUT --header "PRIVATE-TOKEN: $PIPELINE_ACCESS_TOKEN" \
@@ -72,9 +74,22 @@ deploy-vlocity:
         - |
             for PACKAGE in $VLOCITY_PACKAGES_TO_DEPLOY;
             do
+                PACKAGE=$(echo $PACKAGE | sed 's/sfdx\-source\///g')
+                echo "Checking VBTDeployKey$PACKAGE ..."
+                vlocity_cmt__Value__c=$(sfdx force:data:record:get -s vlocity_cmt__GeneralSettings__c -w "Name=VBTDeployKey$PACKAGE" --json | jq .result.vlocity_cmt__Value__c | tr -d '"')
+                if [ "$(git cat-file -t $vlocity_cmt__Value__c)" != "commit" ]; then
+                  echo "Commit stored in Vlocity Deployment Key not found in repository. Aborting to prevent full deployment" 1>&2;
+                  exit 1
+                fi
+            done
+        - |
+            for PACKAGE in $VLOCITY_PACKAGES_TO_DEPLOY;
+            do
                 npx vlocity -sfdx.username Org -job $PACKAGE/vlocity.yaml packDeploy --verbose true --simpleLogging true
                 npx vlocity -sfdx.username Org -job $PACKAGE/vlocity.yaml packRetry --verbose true --simpleLogging true
             done
         - |
             curl --request PUT --header "PRIVATE-TOKEN: $PIPELINE_ACCESS_TOKEN" \
               "$CI_API_V4_URL/projects/$CI_PROJECT_ID/variables/${DESTINATION_ENVIRONMENT}_VLOCITY_LAST_DEPLOYMENT_COMMIT_SHA" --form "value=$CI_COMMIT_SHA"
+        - sf apex run --file ./scripts/apex/AllEnvironments/vlocityTemplateActivation.apex || true # ideally filtering if changes contain any template
+        - npm install puppeteer && node ./scripts/node/AllEnvironments/omniscriptLWCActivation.js || true #  ideally filtering if changes contain LWC OS
